apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Defines how to deploy the application server
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "{{ .Values.name }}:latest"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
    template.alpha.openshift.io/wait-for-ready: "true"
    service.alpha.openshift.io/dependencies: |-
      [
        { 
          "name": "{{ .Values.database_service_name }}",
          "kind": "Deployment"
        }
      ]
  labels:
    app: cakephp-mysql
    template: cakephp-mysql
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.name }}
  strategy:
    recreateParams:
      pre:
        execNewPod:
          command:
          - ./migrate-database.sh
          containerName: cakephp-mysql
        failurePolicy: Retry
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
      name: {{ .Values.name }}
    spec:
      containers:
      - env:
        - name: DATABASE_SERVICE_NAME
          value: "{{ .Values.database_service_name }}"
        - name: PHP_CLEAR_ENV
          value: "OFF"
        - name: DATABASE_NAME
          value: "{{ .Values.database_name }}"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ .Values.name }}
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ .Values.name }}
        - name: CAKEPHP_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              key: cakephp-secret-token
              name: {{ .Values.name }}
        - name: CAKEPHP_SECURITY_SALT
          valueFrom:
            secretKeyRef:
              key: cakephp-security-salt
              name: {{ .Values.name }}
        - name: OPCACHE_REVALIDATE_FREQ
          value: "{{ .Values.opcache_revalidate_freq }}"
        image: " "
        livenessProbe:
          httpGet:
            path: /health.php
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 3
        name: cakephp-mysql
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health.php
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 60
          timeoutSeconds: 3
        resources:
          limits:
            memory: {{ .Values.memory_limit }}
