#!/bin/bash

THISDIR=$(dirname ${BASH_SOURCE[0]})

git show -s

if python3 -c 'import sys; sys.exit(0 if sys.version_info < (3,13) else 1)'; then
  PYTHON_VERSION="3.12"
else
  PYTHON_VERSION="3"
fi

if [[ -z "$1" ]]; then
  echo "Usage: $0 <testname>"
  echo "Available tests: httpd mariadb mysql nginx postgresql redis php perl nodejs python ruby valkey imagestreams"
  exit 1
fi

if [[ "$1" == "imagestreams" ]]; then
  cd "${THISDIR}" && "python${PYTHON_VERSION}" -m pytest -s -rA --showlocals -vv test_*_imagestreams.py
else
  cd "${THISDIR}" && "python${PYTHON_VERSION}" -m pytest -s -rA --showlocals -vv test_${1}_*.py
fi
